name: Prettier action

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier
        run: pnpm prettier
      - name: Push the lint changes
        run: git config user.name "dahliaOS-Bot" && git config user.email dahliaosofficial@gmail.com && git commit -am "Prettified code" && git push
